---
version: "3.7"
services:
  nginx:
    container_name: nginx
    image: docker.io/nginx
    ports:
      - 80:80
      - 8443:443
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./scanner:/usr/share/nginx/html
      - ./ssl:/usr/share/nginx/ssl
