---
version: "3.7"
services:
  nginx:
    container_name: gate_nginx
    build: ./nginx/
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf.d:/etc/nginx/conf.d
      - ./scanner:/usr/share/nginx/html
      - ./ssl:/usr/share/nginx/ssl
