---
version: "3.7"
services:
  nginx:
    container_name: gate_nginx
    build: ./nginx/
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf.d:/etc/nginx/conf.d
      - ./scanner:/usr/share/nginx/html
      - ./ssl:/usr/share/nginx/ssl
    environment:
      - eeapi_url=eeapi_url=https://checkin.goingnowhere.org:2443
      - eeapi_session=fake_session_token
  eeapi:
    container_name: gate_eeapi
    build: ./eeapi/
    volumes:
      - ./eeapi/:/usr/src/app
